### ISSUE TITLE
Is it possible to set every particle's position and color ?

### ISSUE THREAD

**Issue by akashcastelino** [Robert-K/gpu-particles#2]
Hi,
Thanks for open sourcing a great project !

I wanted to inquire if I can set each particles position and color at runtime through script ?

**Comment by Robert-K** [comment]
Hi,
I appreciate your appreciation! 😄

Most (if not all) simulation parameters can be modified via code.
**BUT:** the particle simulation takes place on the GPU with as little interaction between CPU and GPU as possible. That's what makes this so fast/efficient. Technically it is possible to read buffers into arrays, modify them and write into the buffers again. However, that would be really inefficient and slow.

Why do you want to set each particle's position? What effect do you want to achieve?
Only setting the initial position would be possible with minor modifications to the code.

**Comment by akashcastelino** [comment]
I am trying to use your particle system to visualize a point cloud stream. Hence, around 1.3 million particles would be required which is not possible with the built-in Unity Shuriken particle system. 
For this, I am receiving each particles color and position every frame but wanted to know if I could set these positions and colors to each particle respectively.

**Comment by Robert-K** [comment]
So you don't require any particle simulation? In that case you might consider looking into the code and just using the renderer. It's a script/shader combination which takes a buffer with position, color and size arguments and draws it in the scene (using a much faster approach in the unfinished V2 ^^).

**Comment by andybak** [comment]
Not wanted to hijack this but I've been dabbling in similar things and have been investigating the new VFX Graph particle system in preview in Unity 2018.

Keijiro has actually modified his point cloud project to talk directly to VFX Graph and it works very well: https://github.com/keijiro/Pcx

However - his old rendering methods might suit you better depending on what you want to do.

I'd be happy to compare notes on point cloud stuff. I'm andy@ixxy.co.uk or @andybak on Twitter.

**Comment by Robert-K** [comment]
Closing this now, feel free to reopen if you have any more questions.
